sudo: required

language: generic

services:
  - docker

before_install:
  - echo "Start creating an image with dockerfile"
  - docker build -t song/docker-react-app -f Dockerfile.dev .

script:
  - docker run -e CI=true song/docker-react-app npm run test -- --coverage

after_success:
  - echo "Test Success"
